name: Build App
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.2
     
      - name: Install npm
        run: npm install @nodert-win10/windows.graphics.imaging
     
      - name: Install Node Dependencies
        run: npm install --legacy-peer-deps
